# Chapter 1

In [ ]:
!pip install -U spacy[cuda110,transformers,lookups]==3.0.3
!pip install -U spacy-lookups-data==1.0.0
!pip install cupy-cuda110==8.5.0
!python -m spacy download en_core_web_trf

Collecting spacy==3.0.3 (from spacy[cuda110,lookups,transformers]==3.0.3)
  Downloading spacy-3.0.3.tar.gz (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 71.3 MB/s eta 0:00:00
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Collecting spacy-lookups-data==1.0.0
  Downloading spacy_lookups_data-1.0.0-py2.py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from spacy-lookups-data==1.0.0) (80.10.2)
Downloading spacy_lookups_data-1.0.0-py2.py3-none-any.whl (93.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.4/93.4 MB 8.9 MB/s eta 0:00:00
Installing collected packages: spacy-lookups-data
Successfully installed spacy-lookups-data-1.0.0
ERROR: Could not find a version that satisfies the requirement cupy-cuda110==8.5.0 (from versions: none)
ERROR: No matching distribution found for cupy-cuda110==8.5.0
Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 4.3 MB/s eta 0:00:00
Collecting spacy-curated-transformers<1.0.0,>=0.2.2 (from en-core-web-trf==3.8.0)
  Downloading spacy_curated_transformers-0.3.1-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting curated-transformers<0.2.0,>=0.1.0 (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading curated_transformers-0.1.1-py2.py3-none-any.whl.metadata (965 bytes)
Collecting curated-tokenizers<0.1.0,>=0.0.9 (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading curated_tokenizers-0.0.10-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (2.0 kB)
Requirement already satisfied: torch>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.11.0+cu130)
Requirement already satisfied: regex>=2022 in /usr/local/lib/python3.13/dist-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.11.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.0.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.12.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (13.0.85)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.8.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.0.3)
Downloading spacy_curated_transformers-0.3.1-py2.py3-none-any.whl (237 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.9/237.9 kB 10.5 MB/s eta 0:00:00
Downloading curated_tokenizers-0.0.10-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 107.4 MB/s eta 0:00:00
Downloading curated_transformers-0.1.1-py2.py3-none-any.whl (25 kB)
Installing collected packages: curated-tokenizers, curated-transformers, spacy-curated-transformers, en-core-web-trf
Successfully installed curated-tokenizers-0.0.10 curated-transformers-0.1.1 en-core-web-trf-3.8.0 spacy-curated-transformers-0.3.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

## Tokenization

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm") # kiçikölçülü, ingilis dilinə əsaslanan veb-modeli

In [ ]:
sentence = nlp.tokenizer("We live in Paris.")
print(f"The number of tokens: {len(sentence)}")

The number of tokens: 5

In [ ]:
for words in sentence:
  print(f"The token: {words}")

The token: We
The token: live
The token: in
The token: Paris
The token: .

In [ ]:
import pandas as pd
import os

cwd = os.getcwd()
cwd

'/content'

In [ ]:
# Jeopardy questions
# data = pd.read_csv(cwd+'/data/jeopardy_questions/jeopardy_questions.csv')
# data = pd.DataFrame(data=data)

In [ ]:
!kaggle datasets download tunguz/200000-jeopardy-questions

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/tunguz/200000-jeopardy-questions
License(s): other
Downloading 200000-jeopardy-questions.zip to /content
100% 11.5M/11.5M [00:00<00:00, 41.5MB/s]

In [ ]:
!unzip /content/200000-jeopardy-questions.zip

Archive:  /content/200000-jeopardy-questions.zip
  inflating: JEOPARDY_CSV.csv

In [ ]:
data = pd.read_csv('/content/JEOPARDY_CSV.csv')
data.columns = map(lambda x: x.lower().strip(), data.columns)

In [ ]:
# reduce the data size
data = data[:1000]

In [ ]:
data['question_tokens'] = data['question'].apply(lambda x: nlp(x))

In [ ]:
# first question as a sample
example_question = data.question[0]
example_question_tokens = data.question_tokens[0]

In [ ]:
example_question

"For the last 8 years of his life, Galileo was under house arrest for espousing this man's theory"

In [ ]:
for token in example_question_tokens:
  print(token)

For
the
last
8
years
of
his
life
,
Galileo
was
under
house
arrest
for
espousing
this
man
's
theory

## Part-of-speech (POS) tagging

In [ ]:
for token in example_question_tokens:
  print(token.text, token.pos_, spacy.explain(token.pos_))

For ADP adposition
the DET determiner
last ADJ adjective
8 NUM numeral
years NOUN noun
of ADP adposition
his PRON pronoun
life NOUN noun
, PUNCT punctuation
Galileo PROPN proper noun
was AUX auxiliary
under ADP adposition
house NOUN noun
arrest NOUN noun
for ADP adposition
espousing VERB verb
this DET determiner
man NOUN noun
's PART particle
theory NOUN noun

## Dependency Parsing tags

In [ ]:
for token in example_question_tokens:
  print(token.text, token.dep_, spacy.explain(token.dep_))

For prep prepositional modifier
the det determiner
last amod adjectival modifier
8 nummod numeric modifier
years pobj object of preposition
of prep prepositional modifier
his poss possession modifier
life pobj object of preposition
, punct punctuation
Galileo nsubj nominal subject
was ROOT root
under prep prepositional modifier
house compound compound
arrest pobj object of preposition
for prep prepositional modifier
espousing pcomp complement of preposition
this det determiner
man poss possession modifier
's case case marking
theory dobj direct object

In [ ]:
# visualize the dependency parse
from spacy import displacy

displacy.render(example_question_tokens, style='dep', jupyter=True, options={"distance": 120})

In [ ]:
print(dir(spacy))

['Any', 'Config', 'ConfigSchema', 'ConfigSchemaInit', 'ConfigSchemaNlp', 'ConfigSchemaPretrain', 'ConfigSchemaTraining', 'Dict', 'Errors', 'Example', 'Iterable', 'Language', 'Path', 'REGISTRY_POPULATED', 'Union', 'Vocab', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_rebuild_ns', '_schema', 'about', 'attrs', 'blank', 'cli', 'compat', 'displacy', 'errors', 'explain', 'git_info', 'glossary', 'info', 'kb', 'lang', 'language', 'lexeme', 'load', 'logger', 'lookups', 'matcher', 'ml', 'morphology', 'parts_of_speech', 'pipe_analysis', 'pipeline', 'populate_registry', 'prefer_gpu', 'registrations', 'registry', 'require_cpu', 'require_gpu', 'schemas', 'scorer', 'setup_default_warnings', 'strings', 'symbols', 'sys', 'tokenizer', 'tokens', 'training', 'ty', 'util', 'vectors', 'vocab']

## Chunking

In [ ]:
# without chunking
for token in nlp("My parents live in New York City."):
  print(token.text)

My
parents
live
in
New
York
City
.

In [ ]:
## with chunking
for chunk in nlp("My parents live in New York City.").noun_chunks:
  print(chunk.text)

My parents
New York City

## Lemmatization

In [ ]:
lemmatization = pd.DataFrame(data=[], columns=["original", "lemmatized"])

In [ ]:
i = 0
for token in example_question_tokens:
  lemmatization.loc[i, "original"] = token.text
  lemmatization.loc[i, "lemmatized"] = token.lemma_
  i += 1

In [ ]:
lemmatization

     original lemmatized
0         For        for
1         the        the
2        last       last
3           8          8
4       years       year
5          of         of
6         his        his
7        life       life
8           ,          ,
9     Galileo    Galileo
10        was         be
11      under      under
12      house      house
13     arrest     arrest
14        for        for
15  espousing    espouse
16       this       this
17        man        man
18         's         's
19     theory     theory

## Named entity recognition (NER)

In [ ]:
example_sentence = "George Washington was an American political leader, \
military general, statesman, and Founding Father who served as the \
first president of the United States from 1789 to 1797.\n"

print(example_sentence)

George Washington was an American political leader, military general, statesman, and Founding Father who served as the first president of the United States from 1789 to 1797.

In [ ]:
doc = nlp(example_sentence)
doc.ents

(George Washington, American, first, the United States, 1789 to 1797)

In [ ]:
for token in doc.ents:
  print(token.text, token.start_char, token.end_char, token.label_)

George Washington 0 17 PERSON
American 25 33 NORP
first 119 124 ORDINAL
the United States 138 155 GPE
1789 to 1797 161 173 DATE

In [ ]:
displacy.render(doc, style='ent', jupyter=True, options={"distance": 120})

## Named entity linking (NEL)

In [ ]:
import requests

# define Google Knowledge Graph API result function
def returnGraphResult(query, key, entityType):
    if entityType == "PERSON":
        google = f"https://kgsearch.googleapis.com/v1/entities:search?query={query}&key={key}"
        resp = requests.get(google)
        url = resp.json()['itemListElement'][0]['result']['detailedDescription']['url']
        description = resp.json()['itemListElement'][0]['result']['detailedDescription']['article']
        return url, description
    else:
        return "no_match", "no_match"

In [ ]:
key = "YOUR_GOOGLE_KNOWLEDGE_GRAPH_API_KEY"

for token in doc.ents:
    if key != "YOUR_GOOGLE_KNOWLEDGE_GRAPH_API_KEY":
        try:
            url, description = returnGraphResult(token.text, key, token.label_)
            print(token.text, token.label_, url, description)
        except Exception as e:
            print(f"Could not fetch details for {token.text}: {e}")
    else:
        print(f"{token.text} ({token.label_}) - [Please set your API key to fetch Graph Results]")

George Washington (PERSON) - [Please set your API key to fetch Graph Results]
American (NORP) - [Please set your API key to fetch Graph Results]
first (ORDINAL) - [Please set your API key to fetch Graph Results]
the United States (GPE) - [Please set your API key to fetch Graph Results]
1789 to 1797 (DATE) - [Please set your API key to fetch Graph Results]

# Chapter 2

## Training with fastai

In [1]:
from fastai.text.all import *
path = untar_data(URLs.IMDB)

```html
<div>
<progress max="144440600" value="144441344"></progress> 100.00% [144441344/144440600 00:10&lt;00:00]</div>

```

In [2]:
dls = TextDataLoaders.from_folder(path, valid='test')

In [3]:
dls.show_batch()