In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
import torch

In [2]:
!curl -L -o wine-quality-dataset.zip\
  https://www.kaggle.com/api/v1/datasets/download/yasserh/wine-quality-dataset

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21984  100 21984    0     0  58456      0 --:--:-- --:--:-- --:--:-- 58456

In [3]:
!unzip /content/wine-quality-dataset.zip

Archive:  /content/wine-quality-dataset.zip
  inflating: WineQT.csv

In [4]:
df = pd.read_csv('/content/WineQT.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [5]:
df['quality'].value_counts()

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

In [6]:
df.drop(['Id'], axis=1, inplace=True)

In [7]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5

In [8]:
X = df.drop(['quality'], axis=1)
y = df['quality'].copy()

In [9]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.2)

In [10]:
X_train.shape, X_valid.shape, X_test.shape

((731, 11), (183, 11), (229, 11))

In [11]:
y_train.shape, y_valid.shape, y_test.shape

((731,), (183,), (229,))

In [12]:
wine_imputer = SimpleImputer(strategy="median")
wine_scaler = StandardScaler()

In [13]:
X_train_transfomer = wine_scaler.fit_transform(X_train)
X_valid_transfomer = wine_scaler.transform(X_valid)
X_test_transfomer = wine_scaler.transform(X_test)

In [14]:
y_min = y.min() # 3-u çıxartmaq üçün

In [15]:
y_train = y_train.to_numpy() - y_min
y_valid = y_valid.to_numpy() - y_min
y_test = y_test.to_numpy() - y_min

In [16]:
train_tensor = TensorDataset(torch.FloatTensor(X_train_transfomer), torch.LongTensor(y_train))
valid_tensor = TensorDataset(torch.FloatTensor(X_valid_transfomer), torch.LongTensor(y_valid))
test_tensor  = TensorDataset(torch.FloatTensor(X_test_transfomer),  torch.LongTensor(y_test))

In [17]:
train_loader = DataLoader(train_tensor, batch_size=32, shuffle=True)
valid_loader = DataLoader(valid_tensor, batch_size=32)
test_loader = DataLoader(test_tensor, batch_size=32)

In [18]:
input_size = X_train_transfomer.shape[1]

model = nn.Sequential(
    nn.Linear(input_size, 1024),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(1024, 256),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(256, 64),
    nn.ReLU(),
    nn.Linear(64, 6)
)

In [23]:
device='cuda'

In [24]:
def train_model(model, criterion, optimizer, train_loader, n_epochs):
    model.train()
    for epoch in range(n_epochs):
        total_loss = 0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            y_pred = model(X_batch)
            # Ensure y_batch is long and squeezed for CrossEntropyLoss
            loss = criterion(y_pred, y_batch.long().squeeze())
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
        print(f"Epoch: {epoch+1}/{n_epochs}, loss: {total_loss:.4f}")

In [25]:
xentropy = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [26]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)

Sequential(
  (0): Linear(in_features=11, out_features=1024, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.3, inplace=False)
  (3): Linear(in_features=1024, out_features=256, bias=True)
  (4): ReLU()
  (5): Dropout(p=0.3, inplace=False)
  (6): Linear(in_features=256, out_features=64, bias=True)
  (7): ReLU()
  (8): Linear(in_features=64, out_features=6, bias=True)
)

In [27]:
train_model(model, xentropy, optimizer, train_loader, 100)

Epoch: 1/100, loss: 4.5339
Epoch: 2/100, loss: 3.6646
Epoch: 3/100, loss: 2.9547
Epoch: 4/100, loss: 3.0957
Epoch: 5/100, loss: 3.4441
Epoch: 6/100, loss: 3.5287
Epoch: 7/100, loss: 3.5420
Epoch: 8/100, loss: 3.6545
Epoch: 9/100, loss: 3.5486
Epoch: 10/100, loss: 2.8684
Epoch: 11/100, loss: 3.1998
Epoch: 12/100, loss: 3.5453
Epoch: 13/100, loss: 3.0337
Epoch: 14/100, loss: 3.0492
Epoch: 15/100, loss: 2.6922
Epoch: 16/100, loss: 2.6322
Epoch: 17/100, loss: 3.0559
Epoch: 18/100, loss: 2.6605
Epoch: 19/100, loss: 3.2277
Epoch: 20/100, loss: 2.6559
Epoch: 21/100, loss: 2.7106
Epoch: 22/100, loss: 2.1910
Epoch: 23/100, loss: 3.0992
Epoch: 24/100, loss: 3.3835
Epoch: 25/100, loss: 2.6784
Epoch: 26/100, loss: 2.3399
Epoch: 27/100, loss: 2.3830
Epoch: 28/100, loss: 2.5078
Epoch: 29/100, loss: 1.9525
Epoch: 30/100, loss: 3.2617
Epoch: 31/100, loss: 3.4000
Epoch: 32/100, loss: 1.6758
Epoch: 33/100, loss: 3.0637
Epoch: 34/100, loss: 3.0004
Epoch: 35/100, loss: 2.6616
Epoch: 36/100, loss: 2.1489
Epoch: 37/100, loss: 2.1088
Epoch: 38/100, loss: 2.1172
Epoch: 39/100, loss: 2.3829
Epoch: 40/100, loss: 2.4105
Epoch: 41/100, loss: 2.3632
Epoch: 42/100, loss: 2.1251
Epoch: 43/100, loss: 2.2332
Epoch: 44/100, loss: 1.9343
Epoch: 45/100, loss: 3.0672
Epoch: 46/100, loss: 1.7957
Epoch: 47/100, loss: 1.5749
Epoch: 48/100, loss: 2.1231
Epoch: 49/100, loss: 2.2163
Epoch: 50/100, loss: 2.3206
Epoch: 51/100, loss: 2.5538
Epoch: 52/100, loss: 2.0104
Epoch: 53/100, loss: 2.6775
Epoch: 54/100, loss: 2.4838
Epoch: 55/100, loss: 2.7318
Epoch: 56/100, loss: 1.8895
Epoch: 57/100, loss: 2.3243
Epoch: 58/100, loss: 1.9489
Epoch: 59/100, loss: 2.4837
Epoch: 60/100, loss: 2.1125
Epoch: 61/100, loss: 2.3968
Epoch: 62/100, loss: 2.4426
Epoch: 63/100, loss: 2.3415
Epoch: 64/100, loss: 1.9030
Epoch: 65/100, loss: 1.6340
Epoch: 66/100, loss: 1.9088
Epoch: 67/100, loss: 2.3022
Epoch: 68/100, loss: 1.7544
Epoch: 69/100, loss: 2.1064
Epoch: 70/100, loss: 1.9203
Epoch: 71/100, loss: 1.6580
Epoch: 72/100, loss: 2.0329
Epoch: 73/100, loss: 2.0407
Epoch: 74/100, loss: 1.6573
Epoch: 75/100, loss: 1.6780
Epoch: 76/100, loss: 1.8852
Epoch: 77/100, loss: 2.2759
Epoch: 78/100, loss: 1.7087
Epoch: 79/100, loss: 1.3648
Epoch: 80/100, loss: 1.6792
Epoch: 81/100, loss: 1.7349
Epoch: 82/100, loss: 2.0169
Epoch: 83/100, loss: 1.8714
Epoch: 84/100, loss: 1.4876
Epoch: 85/100, loss: 1.5224
Epoch: 86/100, loss: 1.8329
Epoch: 87/100, loss: 1.4624
Epoch: 88/100, loss: 1.7565
Epoch: 89/100, loss: 1.5199
Epoch: 90/100, loss: 1.6045
Epoch: 91/100, loss: 0.8646
Epoch: 92/100, loss: 1.4249
Epoch: 93/100, loss: 1.3693
Epoch: 94/100, loss: 1.5888
Epoch: 95/100, loss: 1.1005
Epoch: 96/100, loss: 1.4727
Epoch: 97/100, loss: 1.8082
Epoch: 98/100, loss: 1.3324
Epoch: 99/100, loss: 2.0708
Epoch: 100/100, loss: 1.9037